# Generated by Django 4.2.4 on 2023-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_remove_userprofile_department_userprofile_department'),
        ('folder', '0002_alter_folder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='department',
            field=models.ManyToManyField(related_name='folders', to='userprofiles.department'),
        ),
    ]
