# Generated by Django 4.2.4 on 2023-08-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_remove_userprofile_department_userprofile_department'),
        ('folder', '0003_folder_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='department',
        ),
        migrations.AddField(
            model_name='folder',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='userprofiles.department'),
            preserve_default=False,
        ),
    ]
