version: '3.8'

services:
  eportal:
    build: .
    container_name: eportal
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
      - static_volume:/app/static  # <-- bind the static volume
      - media_volume:/app/media  # <-- bind the media volume
    ports:
      - "8000:8000"

    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER="redis://redis:6379/0"
      - CELERY_BACKEND="redis://redis:6379/0"
    depends_on:
      - redis
      - pgdb
    networks:
      - nginx_network

  celery:
    build: .
    restart: always
    command: celery -A core worker  -l INFO 
    volumes:
      - .:/app

    depends_on: 
      - eportal
      - redis
    networks:
      - nginx_network

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - nginx_network
    

  pgdb:
    image: postgres:15-alpine
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
    
volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
  pgdata: