# Generated by Django 4.2.4 on 2023-08-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_remove_folder_department_folder_department'),
        ('document', '0004_alter_document_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='folder.folder'),
            preserve_default=False,
        ),
    ]
