# # Generated by Django 4.2.4 on 2023-08-14 06:54

# import accounts.models
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
# import django.utils.timezone


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ('auth', '0012_alter_user_first_name_max_length'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='User',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('password', models.CharField(max_length=128, verbose_name='password')),
#                 ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
#                 ('first_name', models.CharField(blank=True, default='', max_length=255)),
#                 ('is_active', models.BooleanField(default=False)),
#                 ('is_superuser', models.BooleanField(default=False)),
#                 ('is_staff', models.BooleanField(default=False)),
#                 ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('last_login', models.DateTimeField(blank=True, null=True)),
#                 ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
#                 ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
#             ],
#             options={
#                 'verbose_name': 'User',
#                 'verbose_name_plural': 'Users',
#             },
#             managers=[
#                 ('objects', accounts.models.CustomUserManager()),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Department',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=255)),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#                 ('modified_at', models.DateTimeField(auto_now=True)),
#                 ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#                 ('staff', models.ManyToManyField(related_name='staff', to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='UserProfile',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('first_name', models.CharField(blank=True, default='', max_length=255)),
#                 ('last_name', models.CharField(blank=True, default='', max_length=255)),
#                 ('telephone', models.CharField(blank=True, default='', max_length=255)),
#                 ('is_active', models.BooleanField(default=True)),
#                 ('profile_picture', models.ImageField(blank=True, default='', upload_to='media')),
#                 ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='accounts.department')),
#                 ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#     ]
